target-version = "py313"
exclude = [
    ".venv",
    ".eggs",
    ".git",
]

[lint]
select = [
    "B",
    "C",
    "E",
    "W",
    "F",
    "FLY",
    "DJ",
    "I",
    "N",
    "S",
    "PLC",
    "RUF",
    "UP",
]
ignore = [
    "E501", # line too long 🤷
]


[lint.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "django",
    "first-party",
    "local-folder"
]
[lint.isort.sections]
"django" = ["django"]


[lint.per-file-ignores]
"**/tests/**/test_*.py" = [
    "S101", # asserts allowed in tests...
]
